[save]
save_dir = "configs"
filename_format = "pulse_control_20260216_"

[connection]
visa_address = "TCPIP0::192.168.0.251::5025::SOCKET"

[common]
v_on = 0.13
v_off = 2.13
frequency = 5000000.0
period = 2e-7
trigger_delay = 3208
resolution_n = 2

[simple_pulse]
pulse_width = 1.2000000000000002e-7
saved_records = [ [ 1e-8, 3200.0,], [ 2.5e-9, 3200.0,], [ 2e-8, 3200.0,], [ 4e-8, 3200.0,], [ 8e-8, 3208.0,], [ 1.2000000000000002e-7, 3208.0,],]

[width_sweep]
width_start = 2.5e-9
width_stop = 1.2000000000000002e-7
width_step = 1e-8
wait_time = 1.0
settling_time = 0.1
trigger_delay_stop = 3112
delay_mode = "table"
delay_table = [ [ 1e-8, 3200.0,], [ 2.5e-9, 3200.0,], [ 2e-8, 3200.0,], [ 4e-8, 3200.0,], [ 8e-8, 3208.0,], [ 1.2000000000000002e-7, 3208.0,],]
step_zones = [ [ 4e-8, 2.5e-9,],]

[delay_sweep]
pulse_width = 1e-8
wait_time = 0.04
delay_start = 0
delay_stop = 6400
delay_step = 16
settling_time = 2.0

[integration]
dmm_visa_address = "ASRL3::INSTR"
trigger_start_voltage = -9.9
trigger_end_voltage = -9.5
sweep_start_voltage = -9.4
poll_interval = 0.2
num_cycles = 0
